-- MySQL Script generated by MySQL Workbench
-- Sun Mar 17 19:21:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registry` DEFAULT CHARACTER SET utf8 ;
USE `registry` ;

-- -----------------------------------------------------
-- Table `registry`.`registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registry`.`registry` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NULL,
  `email` VARCHAR(300) NULL,
  `cel` VARCHAR(15) NULL,
  `type_customer` TINYINT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
